trigger: none
pool:
  name: 'BizagiTesting'

variables:
  - group: tokens

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "pom.xml"
      options: "-Drepo.password=$(PAT) -s settings.xml"
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'