package payLoads;

public class CreateCases {
	
	
	public static String  CreateCasesAPI() {
		
		
		String Payload = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tem=\"http://tempuri.org/\">\r\n"
				+ "   <soapenv:Header/>\r\n"
				+ "   <soapenv:Body>\r\n"
				+ "      <tem:createCases>\r\n"
				+ "         <!--Optional:-->\r\n"
				+ "         <tem:casesInfo>\r\n"
				+ "            <BizAgiWSParam>\r\n"
				+ "               <!--domain: hardcoded. Must be corrected to OMCORE ASAP. Production will be OMCORE-->\r\n"
				+ "               <domain>OMCORE</domain>\r\n"
				+ "               <!--userName: hardcoded. Must be correct to a special account ASAP. Production will be a special account..-->\r\n"
				+ "               <userName>x473215</userName>\r\n"
				+ "               <Cases>\r\n"
				+ "                  <Case>\r\n"
				+ "                     <!--Process: hardcoded-->\r\n"
				+ "                     <Process>CustomerEngagementBranch</Process>\r\n"
				+ "                     <Entities>\r\n"
				+ "                        <OMmCustomerEngagement>\r\n"
				+ "                           <!--kChannelType: hardcoded TC code-->\r\n"
				+ "                           <kChannelType businessKey=\"iCode=1\"/>\r\n"
				+ "                           <kParentSystemCE>\r\n"
				+ "                              <!--kSystem: hardcoded TC code-->\r\n"
				+ "                              <kSystem businessKey=\"iCode=1046600034\"/>\r\n"
				+ "                              <!--sParentSystemNumber1: Summit Incident number-->\r\n"
				+ "                              <sParentSystemNumber1>RENE</sParentSystemNumber1>\r\n"
				+ "                              <!--sParentSystemNumber2: Summit Service Request number-->\r\n"
				+ "                              <sParentSystemNumber2>SERVICEREQUEST456</sParentSystemNumber2>\r\n"
				+ "                              <!--dTimeOfVisit: start time of the Summit customer engagement process. Out of scope for Release 1. Send through null tag-->\r\n"
				+ "                              <dTimeOfVisit>2013-07-01T01:01:01-05:00</dTimeOfVisit>\r\n"
				+ "                              <!--kBranch. Code of OMF branch code-->\r\n"
				+ "                              <kBranch businessKey=\"iCode=58444\"/>\r\n"
				+ "                              <!--sCaseCreator: The userid of the person who created the Incident. (usally the Host)-->\r\n"
				+ "                              <sCaseCreator>x473215</sCaseCreator>\r\n"
				+ "                              <!--bExists: True if Customer was found on GCS. False if not found.-->\r\n"
				+ "                              <bExists>true</bExists>\r\n"
				+ "                              <!--kCustomerParty: This is the client/policy holder.-->\r\n"
				+ "                              <kCustomerParty>\r\n"
				+ "                                 <!--kPartyType: TC code. 1 for a Person. 2 for an Organisation-->\r\n"
				+ "                                 <kPartyType businessKey=\"iCode=1\"/>\r\n"
				+ "                                 <!--sGCSClientId: If client found on GCS then GCS client id of the Client-->\r\n"
				+ "                                 <sGCSClientId>K0M3Q8SSLAR5R</sGCSClientId>\r\n"
				+ "                                 <!--sFullName. If Party is Person and found on GCS, then Title + FirstName + AdditionalNames + Surname-->\r\n"
				+ "                                 <!--sFullName. If Party is Person and not found on GCS, then Title + Initials + Surname-->\r\n"
				+ "                                 <!--sFullName. If Party is Organisation, then Name-->\r\n"
				+ "                                 <sFullName>John Doe</sFullName>\r\n"
				+ "                                 <!--kPerson. If party type is Person-->\r\n"
				+ "                                 <kPerson>\r\n"
				+ "                                    <!--kGovernmentIDType: TC code of person's id number type-->\r\n"
				+ "                                    <kGovernmentIDType businessKey=\"iCode=4\"/>\r\n"
				+ "                                    <!--sGovernmentID: person's id/passport number-->\r\n"
				+ "                                    <sGovernmentID>8888888888888</sGovernmentID>\r\n"
				+ "                                    <!--kPrefix. TC code of person's prefix/title-->\r\n"
				+ "                                    <kPrefix businessKey=\"iCode=1046600143\"/>\r\n"
				+ "                                    <!--sFirstName: person's first name-->\r\n"
				+ "                                    <sFirstName>John</sFirstName>\r\n"
				+ "                                    <!--sAdditionalName: person's middle names-->\r\n"
				+ "                                    <sAdditionalNames>Ryan Steven</sAdditionalNames>\r\n"
				+ "                                    <!--sLastName: person's surname-->\r\n"
				+ "                                    <sLastName>Doe</sLastName>\r\n"
				+ "                                    <!--sInitials: person's initials-->\r\n"
				+ "                                    <sInitials>XX</sInitials>\r\n"
				+ "                                    <!--dBirthDate: person's date of birth-->\r\n"
				+ "                                    <dBirthDate>1937-01-10</dBirthDate>\r\n"
				+ "                                 </kPerson>\r\n"
				+ "                                 <!--kOrganisation: If party type is Organisation-->\r\n"
				+ "                                 <kOrganisation>\r\n"
				+ "                                    <!--sRegistrationNumber. Registration number of the organisation-->\r\n"
				+ "                                    <sRegistrationNumber/>\r\n"
				+ "                                    <!--kOrganisationType. TC code of Organisation type-->\r\n"
				+ "                                    <kOrganisationType businessKey=\"iCode=23\"/>\r\n"
				+ "                                 </kOrganisation>\r\n"
				+ "                                 <!--xPhones:. If client found on GCS, then GCS values-->\r\n"
				+ "                                 <!--Additionally, always pass through the telephone number captured on Summit with PhoneType 0 (Unknown), and bPreferred true-->\r\n"
				+ "                                 <xPhones>\r\n"
				+ "                                    <OMmPhone>\r\n"
				+ "                                       <kPhoneType businessKey=\"iCode=1\"/>\r\n"
				+ "                                       <sFullNumber>7211111</sFullNumber>\r\n"
				+ "                                       <bPreferred>true</bPreferred>\r\n"
				+ "                                    </OMmPhone>\r\n"
				+ "                                    <OMmPhone>\r\n"
				+ "                                       <kPhoneType businessKey=\"iCode=1\"/>\r\n"
				+ "                                       <sFullNumber>722222</sFullNumber>\r\n"
				+ "                                       <bPreferred>false</bPreferred>\r\n"
				+ "                                    </OMmPhone>\r\n"
				+ "                                 </xPhones>\r\n"
				+ "                                 <!--xEMails:. If client found on GCS, then GCS values, else no tags-->\r\n"
				+ "                                 <xEMails>\r\n"
				+ "                                    <OMmEmail>\r\n"
				+ "                                       <kEmailType businessKey=\"iCode=1\"/>\r\n"
				+ "                                       <sEmail>yy@xx.com</sEmail>\r\n"
				+ "                                       <bPreferred>true</bPreferred>\r\n"
				+ "                                    </OMmEmail>\r\n"
				+ "                                 </xEMails>\r\n"
				+ "                                 <!--xAddresses:. If client found on GCS, then GCS values, else no tags-->\r\n"
				+ "                                 <xAddresses>\r\n"
				+ "                                    <OMmAddress>\r\n"
				+ "                                       <kAddressType businessKey=\"iCode=1\"/>\r\n"
				+ "                                       <sLine1>sfs</sLine1>\r\n"
				+ "                                       <sLine2>sfsf</sLine2>\r\n"
				+ "                                       <sLine3>sfs</sLine3>\r\n"
				+ "                                       <sLine4>sfssdf</sLine4>\r\n"
				+ "                                       <sPostalCode>111</sPostalCode>\r\n"
				+ "                                       <bPreferred>true</bPreferred>\r\n"
				+ "                                    </OMmAddress>\r\n"
				+ "                                 </xAddresses>\r\n"
				+ "                              </kCustomerParty>\r\n"
				+ "                           </kParentSystemCE>\r\n"
				+ "                        </OMmCustomerEngagement>\r\n"
				+ "                     </Entities>\r\n"
				+ "                  </Case>\r\n"
				+ "               </Cases>\r\n"
				+ "            </BizAgiWSParam>\r\n"
				+ "         </tem:casesInfo>\r\n"
				+ "      </tem:createCases>\r\n"
				+ "   </soapenv:Body>\r\n"
				+ "</soapenv:Envelope>\r\n"
				+ "";
		
		return Payload;
		
	
	}

}
